---

REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp2_tm/design_and_ref_files

APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp2_tm/{{TAG_OR_BRANCH}}/apptainer_cache

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp2_tm/{{TAG_OR_BRANCH}}/hydra-genetics

samples: samples.tsv
units: units.tsv

reference:
  mappability: "{{REFERENCE_DATA}}/poppy_uppsala/cnvkit/access-10kb.mm10.bed"

create_background_file:
  min_dp: 300
  min_af: 0.03

purecn_interval_file:
  genome: "GRCh38"

