---
REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp2_tm/design_and_ref_files

APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp2_tm/{{TAG_OR_BRANCH}}/apptainer_cache

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp2_tm/{{TAG_OR_BRANCH}}/hydra-genetics

resources: "{{POPPY_UU_HOME}}/config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "{{POPPY_UU_HOME}}/config/output_files.yaml"

default_container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.10.2.sif'

modules:
  alignment: v0.5.1
  annotation: v1.0.0
  cnv_sv: "1aa9a68" # v0.5.0
  filtering: v0.3.0
  prealignment: v1.2.0
  qc: v0.4.1
  reports: v0.3.1
  snv_indels: v1.1.0


reference:
  fasta: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta"
  fai: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai"
  dict: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.dict"
  exon_bed: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_coding_exons_added_regions.251003.bed"
  design_bed: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_TE-96463385_hg38_251003.bed"
  design_intervals: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_TE-96463385_hg38_251003.interval_list" #hsmetrics
  design_intervals_gatk_cnv: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/design.preprocessed.interval_list"
  artifacts: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/artifact_panel.tsv"
  artifacts_pindel: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/artifact_panel_pindel.tsv"
  background: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/background_panel.tsv"
  skip_chrs:
    - "chrM"
    - "chr1_KI270706v1_random"
    - "chr1_KI270707v1_random"
    - "chr1_KI270708v1_random"
    - "chr1_KI270709v1_random"
    - "chr1_KI270710v1_random"
    - "chr1_KI270711v1_random"
    - "chr1_KI270712v1_random"
    - "chr1_KI270713v1_random"
    - "chr1_KI270714v1_random"
    - "chr2_KI270715v1_random"
    - "chr2_KI270716v1_random"
    - "chr3_GL000221v1_random"
    - "chr4_GL000008v2_random"
    - "chr5_GL000208v1_random"
    - "chr9_KI270717v1_random"
    - "chr9_KI270718v1_random"
    - "chr9_KI270719v1_random"
    - "chr9_KI270720v1_random"
    - "chr11_KI270721v1_random"
    - "chr14_GL000009v2_random"
    - "chr14_GL000225v1_random"
    - "chr14_KI270722v1_random"
    - "chr14_GL000194v1_random"
    - "chr14_KI270723v1_random"
    - "chr14_KI270724v1_random"
    - "chr14_KI270725v1_random"
    - "chr14_KI270726v1_random"
    - "chr15_KI270727v1_random"
    - "chr16_KI270728v1_random"
    - "chr17_GL000205v2_random"
    - "chr17_KI270729v1_random"
    - "chr17_KI270730v1_random"
    - "chr22_KI270731v1_random"
    - "chr22_KI270732v1_random"
    - "chr22_KI270733v1_random"
    - "chr22_KI270734v1_random"
    - "chr22_KI270735v1_random"
    - "chr22_KI270736v1_random"
    - "chr22_KI270737v1_random"
    - "chr22_KI270738v1_random"
    - "chr22_KI270739v1_random"
    - "chrY_KI270740v1_random"
    - "chrUn_KI270302v1"
    - "chrUn_KI270304v1"
    - "chrUn_KI270303v1"
    - "chrUn_KI270305v1"
    - "chrUn_KI270322v1"
    - "chrUn_KI270320v1"
    - "chrUn_KI270310v1"
    - "chrUn_KI270316v1"
    - "chrUn_KI270315v1"
    - "chrUn_KI270312v1"
    - "chrUn_KI270311v1"
    - "chrUn_KI270317v1"
    - "chrUn_KI270412v1"
    - "chrUn_KI270411v1"
    - "chrUn_KI270414v1"
    - "chrUn_KI270419v1"
    - "chrUn_KI270418v1"
    - "chrUn_KI270420v1"
    - "chrUn_KI270424v1"
    - "chrUn_KI270417v1"
    - "chrUn_KI270422v1"
    - "chrUn_KI270423v1"
    - "chrUn_KI270425v1"
    - "chrUn_KI270429v1"
    - "chrUn_KI270442v1"
    - "chrUn_KI270466v1"
    - "chrUn_KI270465v1"
    - "chrUn_KI270467v1"
    - "chrUn_KI270435v1"
    - "chrUn_KI270438v1"
    - "chrUn_KI270468v1"
    - "chrUn_KI270510v1"
    - "chrUn_KI270509v1"
    - "chrUn_KI270518v1"
    - "chrUn_KI270508v1"
    - "chrUn_KI270516v1"
    - "chrUn_KI270512v1"
    - "chrUn_KI270519v1"
    - "chrUn_KI270522v1"
    - "chrUn_KI270511v1"
    - "chrUn_KI270515v1"
    - "chrUn_KI270507v1"
    - "chrUn_KI270517v1"
    - "chrUn_KI270529v1"
    - "chrUn_KI270528v1"
    - "chrUn_KI270530v1"
    - "chrUn_KI270539v1"
    - "chrUn_KI270538v1"
    - "chrUn_KI270544v1"
    - "chrUn_KI270548v1"
    - "chrUn_KI270583v1"
    - "chrUn_KI270587v1"
    - "chrUn_KI270580v1"
    - "chrUn_KI270581v1"
    - "chrUn_KI270579v1"
    - "chrUn_KI270589v1"
    - "chrUn_KI270590v1"
    - "chrUn_KI270584v1"
    - "chrUn_KI270582v1"
    - "chrUn_KI270588v1"
    - "chrUn_KI270593v1"
    - "chrUn_KI270591v1"
    - "chrUn_KI270330v1"
    - "chrUn_KI270329v1"
    - "chrUn_KI270334v1"
    - "chrUn_KI270333v1"
    - "chrUn_KI270335v1"
    - "chrUn_KI270338v1"
    - "chrUn_KI270340v1"
    - "chrUn_KI270336v1"
    - "chrUn_KI270337v1"
    - "chrUn_KI270363v1"
    - "chrUn_KI270364v1"
    - "chrUn_KI270362v1"
    - "chrUn_KI270366v1"
    - "chrUn_KI270378v1"
    - "chrUn_KI270379v1"
    - "chrUn_KI270389v1"
    - "chrUn_KI270390v1"
    - "chrUn_KI270387v1"
    - "chrUn_KI270395v1"
    - "chrUn_KI270396v1"
    - "chrUn_KI270388v1"
    - "chrUn_KI270394v1"
    - "chrUn_KI270386v1"
    - "chrUn_KI270391v1"
    - "chrUn_KI270383v1"
    - "chrUn_KI270393v1"
    - "chrUn_KI270384v1"
    - "chrUn_KI270392v1"
    - "chrUn_KI270381v1"
    - "chrUn_KI270385v1"
    - "chrUn_KI270382v1"
    - "chrUn_KI270376v1"
    - "chrUn_KI270374v1"
    - "chrUn_KI270372v1"
    - "chrUn_KI270373v1"
    - "chrUn_KI270375v1"
    - "chrUn_KI270371v1"
    - "chrUn_KI270448v1"
    - "chrUn_KI270521v1"
    - "chrUn_GL000195v1"
    - "chrUn_GL000219v1"
    - "chrUn_GL000220v1"
    - "chrUn_GL000224v1"
    - "chrUn_KI270741v1"
    - "chrUn_GL000226v1"
    - "chrUn_GL000213v1"
    - "chrUn_KI270743v1"
    - "chrUn_KI270744v1"
    - "chrUn_KI270745v1"
    - "chrUn_KI270746v1"
    - "chrUn_KI270747v1"
    - "chrUn_KI270748v1"
    - "chrUn_KI270749v1"
    - "chrUn_KI270750v1"
    - "chrUn_KI270751v1"
    - "chrUn_KI270752v1"
    - "chrUn_KI270753v1"
    - "chrUn_KI270754v1"
    - "chrUn_KI270755v1"
    - "chrUn_KI270756v1"
    - "chrUn_KI270757v1"
    - "chrUn_GL000214v1"
    - "chrUn_KI270742v1"
    - "chrUn_GL000216v2"
    - "chrUn_GL000218v1"
    - "chrEBV"

annotate_cnv:
  cnv_genes: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_cnv_annotation.240227.bed"

bamsnap:
  extra: " -coverage_vaf 0.05 -show_soft_clipped -read_thickness 2 -read_gap_height 1 "
  container: "{{APPTAINER_CACHE}}/hydragenetics__bamsnap_0.2.19.sif"

bcbio_variation_recall_ensemble:
  container: '{{APPTAINER_CACHE}}/hydragenetics__bcbio-vc_0.2.6.sif'

bcftools_annotate:
  annotation_db: "{{REFERENCE_DATA}}/poppy_uppsala/small_exac_common_3.hg38.vcf.gz"

bcftools_concat_vcfs:
  extra: " -a "

bcftools_filter_include_region:
  cll: "{{REFERENCE_DATA}}/poppy_uppsala/CLL_genes_for_xlsx.250114.sorted.bed"
  myeloid: "{{REFERENCE_DATA}}/poppy_uppsala/Myeloid_genes_for_xlsx.250114.sorted.bed"
  hotspot: "{{REFERENCE_DATA}}/poppy_uppsala/hotspot_genes_for_xlsx.250602.sorted.bed"

bwa_mem:
  amb: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb"
  ann: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann"
  bwt: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt"
  pac: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac"
  sa: "{{REFERENCE_DATA}}/poppy_uppsala/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa"
  container: '{{APPTAINER_CACHE}}/hydragenetics__bwa_0.7.17.sif'

cnv_html_report:
  cytobands: true
  show_table: true

cnvkit_batch:
  normal_reference: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/cnvkit.PoN.cnn"
  method: hybrid
  container: '{{APPTAINER_CACHE}}/hydragenetics__cnvkit_0.9.9.sif'

cnvkit_call:
  container: '{{APPTAINER_CACHE}}/hydragenetics__cnvkit_0.9.9.sif'

cnvkit_vcf:
  hom_del_limit: 0.47
  het_del_limit: 1.68
  dup_limit: 2.3
  container: '{{APPTAINER_CACHE}}/hydragenetics__cnvkit_0.9.9.sif'

fastp_pe:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastpe_0.20.1.sif'

fastqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastqc_0.11.9.sif'

filter_vcf:
  sample_name_regex: ^([A-Za-z0-9-]+_[NRT]\{1\})$
  germline: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_germline.yaml"
  somatic: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_somatic.yaml"
  somatic_hard: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_somatic.yaml"
  pindel: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_pindel.yaml"
  cnv_hard_filter: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_cnv.yaml"

gatk_collect_allelic_counts:
  SNP_interval: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_cnv100.241211.interval_list"
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_denoise_read_counts:
  normal_reference: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/gatk.PoN.hdf5"
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_model_segments:
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_mutect2:
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_mutect2_filter:
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_mutect2_gvcf:
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

gatk_mutect2_merge_stats:
  container: "{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.1.9.0.sif"

merge_af_complex_variants:
  merge_method: "sum"

merge_cnv_json:
  cytobands: "{{POPPY_UU_HOME}}/config/cytoBand.hg38.txt"
  annotations:
    - "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_cnv_annotation.240227.bed"
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf.gz
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.filter.cnv_hard_filter.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.vcf.gz

mosdepth_bed:
  container: "{{APPTAINER_CACHE}}/hydragenetics__mosdepth_0.3.2.sif"

multiqc:
  container: "{{APPTAINER_CACHE}}/hydragenetics__multiqc_1.21.sif"
  reports:
    DNA:
      config: "{{POPPY_UU_HOME}}/config/config_multiqc.yaml"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.per-base.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.thresholds.bed.gz"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt" #inga general stats
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "versions/update_poppy.temp"

picard_collect_alignment_summary_metrics:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

picard_collect_duplication_metrics:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

picard_collect_gc_bias_metrics:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

picard_collect_hs_metrics:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

picard_collect_insert_size_metrics:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

picard_mark_duplicates:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif"

pindel_call:
  extra: "-x 2 -B 60" #x och B?
  include_bed: "{{REFERENCE_DATA}}/poppy_uppsala/Twist_myeloid_pindel_240628.bed"
  container: "{{APPTAINER_CACHE}}/hydragenetics__pindel_0.2.5b9.sif"

pindel_update_vcf:
  container: "{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.4.sif"

pindel2vcf:
  extra: "-e 10 -mc 10 -is 5 -he 0.01 -G" # num reads support
  refname: "GCA_000001405.15_GRCh38_no_alt"
  refdate: "2022"
  container: "{{APPTAINER_CACHE}}/hydragenetics__pindel_0.2.5b9.sif"

purecn:
  genome: GRCh38
  normaldb: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/purecn_normal_db.rds"
  intervals: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/purecn_targets_intervals.txt"
  mapping_bias_file: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/purecn_mapping_bias.rds"
  container: "{{APPTAINER_CACHE}}/hydragenetics__purecn_2.2.0.sif"

purecn_coverage:
  intervals: "{{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/purecn_targets_intervals.txt"
  container: "{{APPTAINER_CACHE}}/hydragenetics__purecn_2.2.0.sif"

results_report_xlsx:
  wanted_transcripts: "{{REFERENCE_DATA}}/poppy_uppsala/tm_mane_transcript.240404.txt"

svdb_merge:
  tc_method:
    - name: purecn
      cnv_caller:
        - cnvkit
        - gatk
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk
  container: "{{APPTAINER_CACHE}}/hydragenetics__svdb_2.6.0.sif"

svdb_query:
  db_string: "--db {{REFERENCE_DATA}}/poppy_uppsala/NovaSeq/svdb_cnv.vcf --out_frq Normal_AF --out_occ Normal_NovaSeq"
  container: "{{APPTAINER_CACHE}}/hydragenetics__svdb_2.6.0.sif"

vardict:
  container: "{{APPTAINER_CACHE}}/hydragenetics__vardict_1.8.3.sif"
  extra: " -Q 1 --nosv "
  bed_columns: "-c 1 -S 2 -E 3"

vep:
  vep_cache: "{{REFERENCE_DATA}}/poppy_uppsala/VEP"
  container: '{{APPTAINER_CACHE}}/ensemblorg__ensembl-vep_release_111.sif'
  mode: "--offline --cache --merged "
  extra: " --assembly GRCh38 --check_existing --pick --variant_class --everything --pick_order mane_select,mane_plus_clinical,canonical,biotype,rank,appris,tsl,ccds,length,ensembl,refseq"

vt_decompose:
  container: "{{APPTAINER_CACHE}}/hydragenetics__vt_2015.11.10.sif"

vt_normalize:
  container: "{{APPTAINER_CACHE}}/hydragenetics__vt_2015.11.10.sif"
